server:
  port: 8150

spring:
  datasource:
    url: jdbc:mysql://104.248.73.1:3306/smartfines?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: "b0e5fffb56bfc845e77bf53d69f567dd313b78b92c36f144"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mail:
    host: smtp.example.com
    port: 587
    username: thanu10
    password: password01g
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: hello-darkness-my-old-friend-by-robert-downney-jr
    access-token-expiration-minutes: 60
  cors:
    allowed-origins:
      - http://localhost:5173
  receipts:
    storage-path: ./storage/receipts

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
